# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='x',
        ),
        migrations.RemoveField(
            model_name='human',
            name='y',
        ),
        migrations.AddField(
            model_name='human',
            name='coord_x',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='coord_y',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
